config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#index"
  get '/tracks', to: 'tracks#index'
  get '/tracks/search', to: 'tracks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_and_belongs_to_many :track
    validates :votes, presence: true
    validates :name, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
    has_and_belongs_to_many :track
    validates :name, presence: true
    validates :title, presence: true
    validates :artist, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def autentication
      client_id = Rails.application.credentials.spotify[:client_id]
      client_secret = Rails.application.credentials.spotify[:client_secret]
      RSpotify.authenticate(client_id, client_secret)
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index; end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    before_action :autentication

    def index
      @tracks = Track.all
    end

    def search
      title = params[:title]
      if title
        @results = RSpotify::Track.search(title)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer d-flex text-left justify-content-end p-3">
    <small>
        Playlist Voter by <a href="https://twitter.com/redacuve">Redacuve</a> 2020
    </small>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark_shades">
  <a class="navbar-brand" href="<%= root_path %>"><img src="<%= asset_path 'playlist_voter.png' %>" alt="Playlist Voter" height=40></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Playlists</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">Account</a>
        <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="dropdown04">
          <a class="dropdown-item" href="#">Profile</a>
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Log Out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PlaylistVoter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="text-center jumbotron">   
    <h1>Welcome to the Playlist Voter</h1>
    <h2>This is the Home Page</h2>
    <h4>You can:</h4>
    <ul>
    <li>See the hottest playlist</li>
    <li>Sign Up</li>
    </ul>
</div>

app/views/tracks/index.html.erb
<h1>Tracks index</h1>
<h2>Search Track</h2>
<%= form_with(url: tracks_search_path, method: "get", local: true, class: "form-inline") do |f| %>
  <%= f.label :title, "Track Title:", class: "mr-2" %>
  <%= f.text_field :title, class: "form-control mr-2 mb-2 mb-sm-0", placeholder: "Search Track" %>
  <%= f.submit "Search", class: "btn btn-secondary" %>
<% end %>

app/views/tracks/search.html.erb
<% if !@results.blank? %>
    <h1 class="h2">Searched track Results:</h1>
    <div class="tracks-container container">
    <div class="row d-none d-md-flex">
        <div class="h2 col-3 text-light_accent">Image</div>
        <div class="col-9 row">
            <div class="h2 col-4 text-main">Title</div>
            <div class="h2 col-4 text-dark_accent">Artist</div>
            <div class="h2 col-4 text-dark_shades">Album</div>
        </div>
    </div>
    <% @results.each do |result| %>
        <div class="p-3 p-sm-1 track row align-items-center">
            <div class="track-img-container col-4 col-md-3 text-center">
                <img src="<%= result.album.images[2]["url"] %>">
            </div>
            <div class="col-8 col-md-9 row">
            <span class="col-12 col-md-4 border-md border-main"><%= result.name %></span>
            <span class="col-12 col-md-4 border-md border-dark_accent"><%= result.artists[0].name %></span>
            <span class="col-12 col-md-4 border-md border-dark_shades"><%= result.album.name %></span>
            </div>
        </div>
    <% end %>
    </div>
<% elsif @results %>
    <h1 class="text-danger">No results Found</h1>
<% end %>
<h2>Search Again </h2>
<%= form_with(url: tracks_search_path, method: "get", local: true, class: "form-inline") do |f| %>
  <%= f.label :title, "Track Title:", class: "mr-2" %>
  <%= f.text_field :title, class: "form-control mr-2 mb-2 mb-sm-0", placeholder: "Search Track" %>
  <%= f.submit "Search", class: "btn btn-secondary" %>
<% end %>